// Test Execution Orchestrator v1 — Warning codes.

export const TestWarningCode = {
  TEST_MANUAL: 'TEST_MANUAL',
  TEST_NO_ASSERTIONS: 'TEST_NO_ASSERTIONS',
  TEST_PARTIAL_EVIDENCE: 'TEST_PARTIAL_EVIDENCE',
  TEST_OPTIONAL_CLEANUP_FAILED: 'TEST_OPTIONAL_CLEANUP_FAILED',
  TEST_UNRESOLVED_DATA: 'TEST_UNRESOLVED_DATA',
  TEST_LOW_CONFIDENCE: 'TEST_LOW_CONFIDENCE',
  TEST_SKIPPED: 'TEST_SKIPPED',
} as const;
