// Standalone spec-unit generation: TestCase JSON → Vitest that runs with
// that case's inputs. No source mapping and no AI. The spec I/O table is
// the function under test until a trusted UnitTargetCodeMapping exists.

import type { TestCase } from './re-export.js';

export interface SpecUnitCase {
  id: string;
  title: string;
  inputs: Record<string, unknown>;
  expected: unknown;
}

export function specInputs(testCase: TestCase): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const input of testCase.inputs ?? []) {
    if (!input?.name) continue;
    out[input.name] = input.value;
  }
  return out;
}

export function specExpected(testCase: TestCase): unknown {
  for (const result of testCase.expectedResults ?? []) {
    const value = result.verificationIntent?.expectedValue;
    if (value !== undefined && value !== null) return value;
    if (result.description) return result.description;
  }
  return undefined;
}

export function toSpecUnitCase(testCase: TestCase): SpecUnitCase | undefined {
  const expected = specExpected(testCase);
  if (expected === undefined) return undefined;
  return {
    id: testCase.id,
    title: testCase.title,
    inputs: specInputs(testCase),
    expected,
  };
}

export function buildSpecApplySource(rows: SpecUnitCase[]): string {
  return [
    '// GENERATED BY TIRAI — spec I/O table (standalone unit, 0 AI).',
    '// specApply(id, inputs) returns the expected value recorded for that TestCase.',
    'const TABLE: Array<{ id: string; inputs: Record<string, unknown>; expected: unknown }> = ',
    `${JSON.stringify(
      rows.map((r) => ({ id: r.id, inputs: r.inputs, expected: r.expected })),
      null,
      2,
    )};`,
    '',
    'export function specApply(id: string, inputs: Record<string, unknown>): unknown {',
    '  const row = TABLE.find((r) => r.id === id);',
    '  if (!row) throw new Error(`TIRAI specApply: no spec row for ${id}`);',
    '  if (JSON.stringify(row.inputs) !== JSON.stringify(inputs)) {',
    '    throw new Error(`TIRAI specApply: inputs do not match TestCase ${id}`);',
    '  }',
    '  return row.expected;',
    '}',
    '',
  ].join('\n');
}

export function buildStandaloneUnitSource(
  spec: SpecUnitCase,
  artifactId: string,
  generationFingerprint: string,
): string {
  return [
    '// ---------------------------------------------------------------------------',
    '// GENERATED BY TIRAI (standalone spec-unit).',
    '// Runs TestCase inputs against the spec I/O table. 0 AI, 0 symbol guesses.',
    '// With a trusted UnitTargetCodeMapping, regenerate to call source instead.',
    `// testCaseId: ${spec.id}`,
    `// artifactId: ${artifactId}`,
    `// generationFingerprint: ${generationFingerprint}`,
    `// sourceFingerprint: __SOURCE_FINGERPRINT__`,
    '// ---------------------------------------------------------------------------',
    "import { describe, it, expect } from 'vitest';",
    "import { specApply } from './_spec-apply';",
    '',
    `const inputs = ${JSON.stringify(spec.inputs)} as Record<string, unknown>;`,
    `const expected = ${JSON.stringify(spec.expected)} as unknown;`,
    '',
    `describe(${JSON.stringify(`${spec.title} [${spec.id}]`)}, () => {`,
    `  it(${JSON.stringify(spec.title)}, () => {`,
    `    const actual = specApply(${JSON.stringify(spec.id)}, inputs);`,
    '    expect(actual).toEqual(expected);',
    '  });',
    '});',
    '',
  ].join('\n');
}
