// Spec preview generation: TestCase JSON → TypeScript preview source that
// shows inputs/expected values side by side. NOT A REAL TEST.
//
// This is an explicit preview artifact only. It does not call application code
// and cannot verify the application. It will never be reported as a unit test
// or application verification result.

import type { TestCase } from './re-export.js';

export interface SpecPreviewCase {
  id: string;
  title: string;
  inputs: Record<string, unknown>;
  expected: unknown;
}

export function specInputs(testCase: TestCase): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const input of testCase.inputs ?? []) {
    if (!input?.name) continue;
    out[input.name] = input.value;
  }
  return out;
}

export function specExpected(testCase: TestCase): unknown {
  for (const result of testCase.expectedResults ?? []) {
    const value = result.verificationIntent?.expectedValue;
    if (value !== undefined && value !== null) return value;
    if (result.description) return result.description;
  }
  return undefined;
}

export function toSpecPreviewCase(testCase: TestCase): SpecPreviewCase | undefined {
  const expected = specExpected(testCase);
  if (expected === undefined) return undefined;
  return {
    id: testCase.id,
    title: testCase.title,
    inputs: specInputs(testCase),
    expected,
  };
}

export function buildSpecPreviewTable(rows: SpecPreviewCase[]): string {
  return [
    '// GENERATED BY TIRAI — spec preview table (NOT A TEST).',
    '// This artifact shows TestCase inputs/expected values for human review.',
    '// It does NOT call application code and cannot verify behavior.',
    '// Do not report this as a unit test or application verification result.',
    'const TABLE: Array<{ id: string; inputs: Record<string, unknown>; expected: unknown }> = ',
    `${JSON.stringify(
      rows.map((r) => ({ id: r.id, inputs: r.inputs, expected: r.expected })),
      null,
      2,
    )};`,
    '',
    'export function specPreview(id: string): { inputs: Record<string, unknown>; expected: unknown } | undefined {',
    '  const row = TABLE.find((r) => r.id === id);',
    '  return row ? { inputs: row.inputs, expected: row.expected } : undefined;',
    '}',
    '',
  ].join('\n');
}

export function buildSpecPreviewSource(
  spec: SpecPreviewCase,
  artifactId: string,
  generationFingerprint: string,
): string {
  return [
    '// ---------------------------------------------------------------------------',
    '// GENERATED BY TIRAI (spec preview artifact — NOT A TEST).',
    '// This file shows inputs/expected values for human review only.',
    '// It does NOT call application code and cannot verify behavior.',
    '// Do not report this as a unit test or application verification result.',
    '// To generate a real unit test, provide a trusted UnitTargetCodeMapping.',
    `// testCaseId: ${spec.id}`,
    `// artifactId: ${artifactId}`,
    `// generationFingerprint: ${generationFingerprint}`,
    '// ---------------------------------------------------------------------------',
    `const inputs = ${JSON.stringify(spec.inputs)} as Record<string, unknown>;`,
    `const expected = ${JSON.stringify(spec.expected)} as unknown;`,
    '',
    `console.log('[TIRAI spec preview] ${spec.id}:', { inputs, expected });`,
    '',
  ].join('\n');
}
