// Unit test generator (Vitest) — Phase 5.2 (spec §8–§13, §15).
//
// Deterministic translation of a canonical TestCase (grounded by a trusted
// UnitTargetCodeMapping + inspected target project symbols) into real Vitest
// test source.
//
// Hard guarantees (mirrors Phase 5.1):
//   * Zero AI calls (intelligence already happened upstream).
//   * Zero guessed symbols: resolution is via TS compiler AST inspection.
//   * Fail-closed: any unresolvable mapping blocks the whole test case.
//   * No source-specific (Excel/Markdown/PDF) branching.

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import prettier from 'prettier';

import type {
  TestCase,
  UnitGenerationInput,
  UnitGenerationResult,
  UnitGenerationMetrics,
  TestCaseGenerationResult,
  TestCaseGenerationStatus,
  GenerationBlockReason,
  GenerationBlockCode,
  UnitTargetCodeMapping,
  UnitAssertionType,
} from './models.js';
import { inspectTargetProject, resolveUnitMapping, type ResolvedUnitMapping } from './target-inspector.js';
import { sha256, artifactIdFrom } from './fingerprint.js';
import { toSpecPreviewCase, buildSpecPreviewTable, buildSpecPreviewSource, type SpecPreviewCase } from './spec-preview.js';

function sanitizeFileName(id: string): string {
  return id.replace(/[^a-zA-Z0-9_-]/g, '_');
}

function blockReasonToCode(reason: GenerationBlockReason): GenerationBlockCode {
  return reason.code;
}

function buildCallExpression(symbolName: string, isMethod: boolean, argLiteral: string): string {
  if (isMethod) {
    const dot = symbolName.indexOf('.');
    const className = symbolName.slice(0, dot);
    const methodName = symbolName.slice(dot + 1);
    return `new ${className}().${methodName}(${argLiteral})`;
  }
  return `${symbolName}(${argLiteral})`;
}

function buildAssertion(
  assertionType: UnitAssertionType,
  isAsyncSymbol: boolean,
  callExpr: string,
  expectedJson: string,
  expectedRaw: unknown,
): { statements: string; needsAwait: boolean } {
  switch (assertionType) {
    case 'deep-equal':
      return { statements: `expect(result).toEqual(${expectedJson});`, needsAwait: false };
    case 'primitive-equal':
      return { statements: `expect(result).toBe(${expectedJson});`, needsAwait: false };
    case 'boolean':
      return {
        statements: `expect(result).toBe(${
          expectedRaw === true ? 'true' : expectedRaw === false ? 'false' : expectedJson
        });`,
        needsAwait: false,
      };
    case 'null':
      return { statements: `expect(result).toBeNull();`, needsAwait: false };
    case 'non-null':
      return { statements: `expect(result).not.toBeNull();`, needsAwait: false };
    case 'throws':
      if (isAsyncSymbol) {
        return {
          statements: `await expect(${callExpr}).rejects.toThrow();`,
          needsAwait: true,
        };
      }
      return { statements: `expect(() => ${callExpr}).toThrow();`, needsAwait: false };
    case 'rejects':
      return {
        statements: `await expect(${callExpr}).rejects.toThrow();`,
        needsAwait: true,
      };
    default:
      throw new Error(`UNSUPPORTED_ASSERTION_TYPE:${assertionType}`);
  }
}

function buildUnitSource(
  testCase: TestCase,
  resolved: ResolvedUnitMapping,
  artifactId: string,
  generationFingerprint: string,
): string {
  const symbol = resolved.symbol!;
  const binding = resolved.binding!;
  const isMethod = symbol.kind === 'method';
  const argsLiteral = binding.argumentValues.map((v) => JSON.stringify(v)).join(', ');
  const callExpr = buildCallExpression(symbol.symbolName, isMethod, argsLiteral);
  const expectedJson = JSON.stringify(binding.expectedValue);

  const assertion = buildAssertion(
    binding.assertionType,
    symbol.isAsync,
    callExpr,
    expectedJson,
    binding.expectedValue,
  );

  const isAsyncBody = symbol.isAsync || assertion.needsAwait;

  let body: string;
  if (isAsyncBody) {
    const prefix = symbol.isAsync && binding.assertionType !== 'throws' && binding.assertionType !== 'rejects'
      ? `const result = await ${callExpr};`
      : '';
    const stmt = assertion.statements;
    body = [prefix, stmt].filter(Boolean).join('\n  ');
  } else {
    body = [
      `const result = ${callExpr};`,
      assertion.statements,
    ].join('\n  ');
  }

  const importLine = symbol.kind === 'method'
    ? `import { ${symbol.symbolName.split('.')[0]} } from ${JSON.stringify(symbol.importPath)};`
    : `import { ${symbol.symbolName} } from ${JSON.stringify(symbol.importPath)};`;

  return [
    '// ---------------------------------------------------------------------------',
    '// GENERATED BY TIRAI Phase 5.2 test-code-generator (Vitest unit tests).',
    '// Trust model: the target symbol is resolved deterministically via TS compiler',
    '// AST inspection; the mapping is explicit. Generation used 0 AI calls and',
    '// guessed 0 symbols. Independently executable via:',
    '//   npx vitest run <this-file>',
    `// testCaseId: ${testCase.id}`,
    `// targetSymbol: ${symbol.symbolName} (${symbol.sourceFile})`,
    `// artifactId: ${artifactId}`,
    `// generationFingerprint: ${generationFingerprint}`,
    `// sourceFingerprint: __SOURCE_FINGERPRINT__`,
    '// ---------------------------------------------------------------------------',
    "import { describe, it, expect } from 'vitest';",
    importLine,
    '',
    `describe(${JSON.stringify(`${testCase.title} [${testCase.id}]`)}, () => {`,
    `  it(${JSON.stringify(testCase.title)}, ${isAsyncBody ? 'async ' : ''}() => {`,
    `  ${body}`,
    '  });',
    '});',
    '',
  ].join('\n');
}

export async function generateUnitTests(
  input: UnitGenerationInput,
): Promise<UnitGenerationResult> {
  const { testCases, profile, targetMappings, options } = input;

  const hasMappedCases = testCases.some((tc) => targetMappings.some((m) => m.testCaseId === tc.id));
  const index = hasMappedCases ? inspectTargetProject(profile) : new Map();
  const targetSymbolsScanned = [...index.values()].reduce((a, l) => a + l.length, 0);

  const caseResults: TestCaseGenerationResult[] = [];
  const generatedFiles: string[] = [];
  const standaloneRows: SpecPreviewCase[] = [];
  let generatedBytes = 0;

  const m = (): UnitGenerationMetrics => ({
    testCasesReceived: 0,
    testCasesGenerated: 0,
    testCasesBlocked: 0,
    targetSymbolsScanned: 0,
    targetSymbolsResolved: 0,
    targetSymbolsAmbiguous: 0,
    targetSymbolsMissing: 0,
    staleMappingsDetected: 0,
    inputMappingsResolved: 0,
    inputMappingsBlocked: 0,
    assertionMappingsResolved: 0,
    assertionMappingsBlocked: 0,
    generatedUnitFiles: 0,
    generatedUnitBytes: 0,
    generationAiCalls: 0,
    aiSymbolGuesses: 0,
    guessedMappings: 0,
    sourceSpecificBranchesInUnitGenerator: 0,
    unsupportedAssertions: 0,
  });
  const metrics = m();
  metrics.testCasesReceived = testCases.length;
  metrics.targetSymbolsScanned = targetSymbolsScanned;

  for (const testCase of testCases) {
    const mapping: UnitTargetCodeMapping | undefined = targetMappings.find(
      (x) => x.testCaseId === testCase.id,
    );
    if (!mapping) {
      const spec = toSpecPreviewCase(testCase);
      if (!spec) {
        metrics.testCasesBlocked++;
        metrics.assertionMappingsBlocked++;
        const reason: GenerationBlockReason = {
          code: 'MISSING_VALUE',
          message: `Test case '${testCase.id}' has no inputs/expected to generate a preview artifact`,
        };
        caseResults.push(blockedCase(testCase, reason));
        continue;
      }
      standaloneRows.push(spec);
      const generationFingerprint = sha256({ testCase, mode: 'preview' });
      const artifactId = artifactIdFrom(`${testCase.id}:${generationFingerprint}`);
      const rawSource = buildSpecPreviewSource(spec, artifactId, generationFingerprint);
      const formatted = await prettier.format(rawSource, { parser: 'typescript' });
      const sourceFingerprint = sha256(formatted);
      const finalSource = formatted.replace('__SOURCE_FINGERPRINT__', sourceFingerprint);
      const outPath = `${options.outputDir}/${sanitizeFileName(testCase.id)}.preview.ts`;
      mkdirSync(dirname(outPath), { recursive: true });
      writeFileSync(outPath, finalSource, 'utf8');
      generatedBytes += Buffer.byteLength(finalSource, 'utf8');
      metrics.generatedUnitBytes = generatedBytes;
      metrics.generatedUnitFiles++;
      generatedFiles.push(outPath);
      caseResults.push({
        testCaseId: testCase.id,
        status: 'preview' as TestCaseGenerationStatus,
        generatedFilePath: outPath,
        artifactId,
        generationFingerprint,
        sourceFingerprint,
        diagnostics: [
          {
            severity: 'info',
            message: `Spec preview artifact (not a test) — no source mapping provided`,
          },
        ],
        trustedMappingsUsed: 0,
        guessedMappings: 0,
      });
      continue;
    }

    const resolved = resolveUnitMapping(testCase, mapping, index, options.outputDir, profile);

    if (resolved.status !== 'RESOLVED') {
      metrics.testCasesBlocked++;
      if (resolved.status === 'AMBIGUOUS') metrics.targetSymbolsAmbiguous++;
      if (resolved.status === 'NOT_FOUND') metrics.targetSymbolsMissing++;
      if (resolved.status === 'STALE_MAPPING') metrics.staleMappingsDetected++;
      if (resolved.status === 'UNRESOLVED_INPUT') metrics.inputMappingsBlocked++;
      if (resolved.status === 'UNSUPPORTED_ASSERTION') {
        metrics.assertionMappingsBlocked++;
        metrics.unsupportedAssertions++;
      }
      caseResults.push(blockedCase(testCase, resolved.reason!));
      continue;
    }

    // RESOLVED
    metrics.targetSymbolsResolved++;
    metrics.inputMappingsResolved += resolved.binding!.argumentValues.length;
    metrics.assertionMappingsResolved++;

    const generationFingerprint = sha256({ testCase, mapping, profile });
    const artifactId = artifactIdFrom(`${testCase.id}:${generationFingerprint}`);
    const rawSource = buildUnitSource(testCase, resolved, artifactId, generationFingerprint);
    const formatted = await prettier.format(rawSource, { parser: 'typescript' });
    const sourceFingerprint = sha256(formatted);
    const finalSource = formatted.replace('__SOURCE_FINGERPRINT__', sourceFingerprint);

    const outPath = `${options.outputDir}/${sanitizeFileName(testCase.id)}.spec.ts`;
    mkdirSync(dirname(outPath), { recursive: true });
    writeFileSync(outPath, finalSource, 'utf8');

    generatedBytes += Buffer.byteLength(finalSource, 'utf8');
    metrics.generatedUnitBytes = generatedBytes;
    metrics.generatedUnitFiles++;
    generatedFiles.push(outPath);

    caseResults.push({
      testCaseId: testCase.id,
      status: 'generated' as TestCaseGenerationStatus,
      generatedFilePath: outPath,
      artifactId,
      generationFingerprint,
      sourceFingerprint,
      diagnostics: [
        {
          severity: 'info',
          message: `Resolved target symbol '${resolved.symbol!.symbolName}' via trusted mapping`,
        },
      ],
      trustedMappingsUsed: 1,
      guessedMappings: 0,
    });
  }

  if (standaloneRows.length > 0) {
    const applyPath = `${options.outputDir}/_spec-preview.ts`;
    mkdirSync(dirname(applyPath), { recursive: true });
    const applySource = await prettier.format(buildSpecPreviewTable(standaloneRows), { parser: 'typescript' });
    writeFileSync(applyPath, applySource, 'utf8');
  }

  metrics.testCasesGenerated = caseResults.filter((c) => c.status === 'generated').length;

  const blocked = metrics.testCasesBlocked;
  const generated = metrics.testCasesGenerated;
  const status: UnitGenerationResult['status'] =
    blocked === 0 ? 'success' : generated === 0 ? 'blocked' : 'partial';

  return {
    framework: 'vitest',
    status,
    generatedFiles,
    caseResults,
    metrics,
    fingerprint: sha256({ caseResults, metrics }),
  };
}

function blockedCase(
  testCase: TestCase,
  reason: GenerationBlockReason,
): TestCaseGenerationResult {
  const generationFingerprint = sha256({ testCase, blocked: reason.code });
  return {
    testCaseId: testCase.id,
    status: 'blocked' as TestCaseGenerationStatus,
    artifactId: artifactIdFrom(`${testCase.id}:blocked:${generationFingerprint}`),
    generationFingerprint,
    sourceFingerprint: sha256({ blocked: reason.code }),
    blockingReason: reason,
    diagnostics: [{ severity: 'blocked', message: reason.message }],
    trustedMappingsUsed: 0,
    guessedMappings: 0,
  };
}

export { blockReasonToCode };
