// ---------------------------------------------------------------------------
// GENERATED BY TIRAI Phase 5.1 test-code-generator.
// Trust model: every locator, action and assertion below is derived from the
// trusted ExecutionMappingIR + UIElementCatalog. Generation used 0 AI calls and
// guessed 0 selectors. This file is independently executable via:
//   npx playwright test <this-file>
// testCaseId: TC-BF-012
// artifactId: tirai-gen-01d5269aa421b8b8
// generationFingerprint: d65da5100be2fa1ac33481fa3850d2246d088d2b5b3d8b50e6bef46c21ae0937
// sourceFingerprint: b149ed103d7dd81a3d088b4d066bb3cf568662856472b4a38f1af4b75316c55c
// ---------------------------------------------------------------------------
import { test, expect } from "@playwright/test";

test("Posts view mode control is usable", async ({ page }) => {
  await page.goto("http://127.0.0.1:3000/posts");
  await expect(page.getByTestId("app-ready")).toHaveText("ready");
  await page.getByTestId("posts-virtual-view").click();
  await expect(page.getByTestId("posts-virtual-view")).toBeEnabled();
});
