// ---------------------------------------------------------------------------
// GENERATED BY TIRAI Phase 5.1 test-code-generator.
// Trust model: every locator, action and assertion below is derived from the
// trusted ExecutionMappingIR + UIElementCatalog. Generation used 0 AI calls and
// guessed 0 selectors. This file is independently executable via:
//   npx playwright test <this-file>
// testCaseId: TC-BF-003
// artifactId: tirai-gen-41e15519de22d3dc
// generationFingerprint: f585880884ad7e4f09105781f98e219ec221b9f85c6ab2c7283bf88e8e5d06d2
// sourceFingerprint: 2793bb9f19a49dcb8bdb5d250cdbb57d375dad5b62b94a9cc76ad6f0f97c4b32
// ---------------------------------------------------------------------------
import { test, expect } from "@playwright/test";

test("Navigation opens the Todos module", async ({ page }) => {
  await page.goto("http://127.0.0.1:3000/");
  await expect(page.getByTestId("app-ready")).toHaveText("ready");
  await page.getByTestId("nav-todos").click();
  await expect(page).toHaveURL(/\/todos/);
});
