// ---------------------------------------------------------------------------
// GENERATED BY TIRAI Phase 5.1 test-code-generator.
// Trust model: every locator, action and assertion below is derived from the
// trusted ExecutionMappingIR + UIElementCatalog. Generation used 0 AI calls and
// guessed 0 selectors. This file is independently executable via:
//   npx playwright test <this-file>
// testCaseId: TC-BF-013
// artifactId: tirai-gen-b7d7c77f25fb2f94
// generationFingerprint: 023d5073fbf8e5f88b2c6a4f463fc09640ab016aa71d15d1045dc8d96bd0ae78
// sourceFingerprint: b4a65c5d0efde780197d70546c77685f86c5be0fc2c2b1e999532bfbf0794983
// ---------------------------------------------------------------------------
import { test, expect } from "@playwright/test";

test("Users page loads", async ({ page }) => {
  await page.goto("http://127.0.0.1:3000/users");
  await expect(page.getByTestId("app-ready")).toHaveText("ready");
  await expect(page.getByTestId("users-heading")).toBeVisible();
});
