// ---------------------------------------------------------------------------
// GENERATED BY TIRAI Phase 5.1 test-code-generator.
// Trust model: every locator, action and assertion below is derived from the
// trusted ExecutionMappingIR + UIElementCatalog. Generation used 0 AI calls and
// guessed 0 selectors. This file is independently executable via:
//   npx playwright test <this-file>
// testCaseId: TC-BF-004
// artifactId: tirai-gen-fbd093364d4890bd
// generationFingerprint: dc0d41e7b50102a2cf189a0a32cc528f9eb953322262772db85808bba0cd6a37
// sourceFingerprint: c9e8c325e744dc97e8b7e21ab24c5a6451a2d663e2304680b9bc98145d2de150
// ---------------------------------------------------------------------------
import { test, expect } from "@playwright/test";

test("Todos page loads", async ({ page }) => {
  await page.goto("http://127.0.0.1:3000/todos");
  await expect(page.getByTestId("app-ready")).toHaveText("ready");
  await expect(page.getByTestId("todos-heading")).toBeVisible();
});
