// ---------------------------------------------------------------------------
// GENERATED BY TIRAI Phase 5.1 test-code-generator.
// Trust model: every locator, action and assertion below is derived from the
// trusted ExecutionMappingIR + UIElementCatalog. Generation used 0 AI calls and
// guessed 0 selectors. This file is independently executable via:
//   npx playwright test <this-file>
// testCaseId: TC-BF-001
// artifactId: tirai-gen-66530dfca6ad5f85
// generationFingerprint: 2d98fe1607c86300250cc80d8db7a5351d571729341f2c8b607e0902cc6a2c41
// sourceFingerprint: 098233f10b6b13a9adc8c0ad09e92f666fe913d18fe8791fa9cd2872b0d825af
// ---------------------------------------------------------------------------
import { test, expect } from "@playwright/test";

test("App shell loads at the root route", async ({ page }) => {
  await page.goto("http://127.0.0.1:3000/");
  await expect(page.getByTestId("app-ready")).toHaveText("ready");
  await expect(page).toHaveTitle("TanStack Full Demo");
});
