// ---------------------------------------------------------------------------
// GENERATED BY TIRAI Phase 5.1 test-code-generator.
// Trust model: every locator, action and assertion below is derived from the
// trusted ExecutionMappingIR + UIElementCatalog. Generation used 0 AI calls and
// guessed 0 selectors. This file is independently executable via:
//   npx playwright test <this-file>
// testCaseId: TC-BF-012
// artifactId: tirai-gen-de64117f276948e7
// generationFingerprint: e771e947cfc993caaef2c052d618573e386d83b68f6d56c2a6ac9f0b117c26d7
// sourceFingerprint: 4be49377de003e717dd37fedef4b295c3be0172101aedbfc2c88d6efb7089797
// ---------------------------------------------------------------------------
import { test, expect } from "@playwright/test";

test("Posts view mode control is usable", async ({ page }) => {
  await page.goto("http://127.0.0.1:3000/posts");
  await expect(page.getByTestId("app-ready")).toHaveText("ready");
  await page.getByTestId("posts-virtual-view").click();
  await expect(page.getByTestId("posts-virtual-view")).toBeEnabled();
});
