// ---------------------------------------------------------------------------
// GENERATED BY TIRAI Phase 5.1 test-code-generator.
// Trust model: every locator, action and assertion below is derived from the
// trusted ExecutionMappingIR + UIElementCatalog. Generation used 0 AI calls and
// guessed 0 selectors. This file is independently executable via:
//   npx playwright test <this-file>
// testCaseId: TC-BF-013
// artifactId: tirai-gen-250c0305b25f9f65
// generationFingerprint: b1f70c60be13c82215c8c342a96895d4659af42ffc1a528a5646bb6ddffdf410
// sourceFingerprint: 92aa4e47d29caddaa0a0adfe59b26287a803efdfe5e6138cba0cf0403fe464fb
// ---------------------------------------------------------------------------
import { test, expect } from "@playwright/test";

test("Users page loads", async ({ page }) => {
  await page.goto("http://127.0.0.1:3000/users");
  await expect(page.getByTestId("app-ready")).toHaveText("ready");
  await expect(page.getByTestId("users-heading")).toBeVisible();
});
