// ---------------------------------------------------------------------------
// GENERATED BY TIRAI Phase 5.1 test-code-generator.
// Trust model: every locator, action and assertion below is derived from the
// trusted ExecutionMappingIR + UIElementCatalog. Generation used 0 AI calls and
// guessed 0 selectors. This file is independently executable via:
//   npx playwright test <this-file>
// testCaseId: TC-BF-002
// artifactId: tirai-gen-4f906787916f185d
// generationFingerprint: cba5ba0367ab92b062b587353594a30bf8bb309128fbf36ff62b7ed1201d1c6b
// sourceFingerprint: 2960df0898a2577030a36b6471326281315762fe94ac6cfbd4b7104cb96c5c86
// ---------------------------------------------------------------------------
import { test, expect } from "@playwright/test";

test("Dashboard is visible", async ({ page }) => {
  await page.goto("http://127.0.0.1:3000/");
  await expect(page.getByTestId("app-ready")).toHaveText("ready");
  await expect(page.getByTestId("dashboard-heading")).toBeVisible();
});
