// ---------------------------------------------------------------------------
// GENERATED BY TIRAI Phase 5.1 test-code-generator.
// Trust model: every locator, action and assertion below is derived from the
// trusted ExecutionMappingIR + UIElementCatalog. Generation used 0 AI calls and
// guessed 0 selectors. This file is independently executable via:
//   npx playwright test <this-file>
// testCaseId: TC-BF-005
// artifactId: tirai-gen-d7f6175b38bc8cb1
// generationFingerprint: 0ef74c0766cac4fa1078572082409840aa673fefd9cbbfa79039b3f4602dbc97
// sourceFingerprint: 3f624c76b770862a086c79fbf8f5aec87c59aaf58d133d39901d61d7e8140614
// ---------------------------------------------------------------------------
import { test, expect } from "@playwright/test";

test("Add Todo rejects an empty title", async ({ page }) => {
  await page.goto("http://127.0.0.1:3000/todos");
  await expect(page.getByTestId("app-ready")).toHaveText("ready");
  await page.getByTestId("add-todo-input").fill("   ");
  await page.getByTestId("add-todo-input").blur();
  await page.getByTestId("add-todo-button").click();
  await expect(page.getByTestId("add-todo-validation")).toContainText(
    "Title is required",
  );
});
