// ---------------------------------------------------------------------------
// GENERATED BY TIRAI Phase 5.1 test-code-generator.
// Trust model: every locator, action and assertion below is derived from the
// trusted ExecutionMappingIR + UIElementCatalog. Generation used 0 AI calls and
// guessed 0 selectors. This file is independently executable via:
//   npx playwright test <this-file>
// testCaseId: TC-BF-007
// artifactId: tirai-gen-8cad45365a0fdda9
// generationFingerprint: 0603ed72d5c63f798cb7c14f5818175187007af4baa5fc3d67811339a3ec735b
// sourceFingerprint: e5ccd08572c28cfa1982f3601577e86e07ce7cfa156434fe0e36fd275b8b1199
// ---------------------------------------------------------------------------
import { test, expect } from "@playwright/test";

test("Todos search input accepts a query", async ({ page }) => {
  await page.goto("http://127.0.0.1:3000/todos");
  await expect(page.getByTestId("app-ready")).toHaveText("ready");
  await page.getByTestId("todo-search").fill("buy milk");
  await expect(page.getByTestId("todo-search")).toHaveValue("buy milk");
});
