// UI Executor v1 — Warning codes.

export enum UIWarningCode {
  UI_TEST_SKIPPED = 'UI_TEST_SKIPPED',
  UI_MAPPING_MISSING = 'UI_MAPPING_MISSING',
  UI_ASSERTION_UNVERIFIABLE = 'UI_ASSERTION_UNVERIFIABLE',
  UI_SCREENSHOT_FAILED = 'UI_SCREENSHOT_FAILED',
  UI_SENSITIVE_FIELD_DETECTED = 'UI_SENSITIVE_FIELD_DETECTED',
  UI_FALLBACK_WAIT = 'UI_FALLBACK_WAIT',
}
