// ---------------------------------------------------------------------------
// Warning codes & helpers
// ---------------------------------------------------------------------------

import type { Warning } from './models.js';

export const WarningCode = {
  SHEET_DIMENSION_UNRELIABLE: 'SHEET_DIMENSION_UNRELIABLE',
  STYLE_PARSE_PARTIAL: 'STYLE_PARSE_PARTIAL',
  FORMULA_CACHED_VALUE_MISSING: 'FORMULA_CACHED_VALUE_MISSING',
  DRAWING_RELATIONSHIP_UNRESOLVED: 'DRAWING_RELATIONSHIP_UNRESOLVED',
  IMAGE_ASSET_MISSING: 'IMAGE_ASSET_MISSING',
  UNSUPPORTED_DRAWING_TYPE: 'UNSUPPORTED_DRAWING_TYPE',
  SHAPE_CONTENT_PARTIAL: 'SHAPE_CONTENT_PARTIAL',
  CHART_CONTENT_NOT_EXTRACTED: 'CHART_CONTENT_NOT_EXTRACTED',
  DRAWING_XML_PARSE_PARTIAL: 'DRAWING_XML_PARSE_PARTIAL',
  CONDITIONAL_FORMATTING_PARTIAL: 'CONDITIONAL_FORMATTING_PARTIAL',
  DXF_STYLE_UNRESOLVED: 'DXF_STYLE_UNRESOLVED',
  PAGE_SETUP_PARTIAL: 'PAGE_SETUP_PARTIAL',
  ARRAY_FORMULA_PARTIAL: 'ARRAY_FORMULA_PARTIAL',
  DATA_VALIDATION_PARTIAL: 'DATA_VALIDATION_PARTIAL',
  TABLE_PARSE_PARTIAL: 'TABLE_PARSE_PARTIAL',
  HYPERLINK_RELATIONSHIP_UNRESOLVED: 'HYPERLINK_RELATIONSHIP_UNRESOLVED',
  COMMENT_FORMAT_PARTIAL: 'COMMENT_FORMAT_PARTIAL',
  THREADED_COMMENT_NOT_SUPPORTED: 'THREADED_COMMENT_NOT_SUPPORTED',
  SHAPE_TEXT_NOT_SUPPORTED: 'SHAPE_TEXT_NOT_SUPPORTED',
  MACRO_CONTENT_NOT_INSPECTED: 'MACRO_CONTENT_NOT_INSPECTED',
  EXTERNAL_LINKS_NOT_FULLY_SUPPORTED: 'EXTERNAL_LINKS_NOT_FULLY_SUPPORTED',
} as const;

export type WarningCodeValue = (typeof WarningCode)[keyof typeof WarningCode];

export function createWarning(
  code: WarningCodeValue,
  message: string,
  sheet?: string,
  cell?: string,
): Warning {
  const w: Warning = { code, message };
  if (sheet !== undefined) w.sheet = sheet;
  if (cell !== undefined) w.cell = cell;
  return w;
}
